version: "3"

services:
  web:
    container_name: home-web
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 1.1.1.1
