name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run new container
        run: |
          docker-compose -f docker-compose.yml up --build --force-recreate -d

      - name: Remove old stopped containers
        run: |
          docker-compose -f docker-compose.yml down || true

      - name: Cleanup old images
        run: |
          docker image prune -af --filter "until=4h"
