name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove old container
        run: |
          docker stop home-web || true
          docker rm home-web || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run new container
        run: |
          docker-compose -f docker-compose.yml up --build -d

  clean:
    runs-on: self-hosted
    needs: build-and-deploy
    steps:
      - name: Clean Docker build cache
        run: docker builder prune -a -f

      - name: Clean all temporary Docker images
        run: docker image prune -f
