name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

          - name: Deploy using Docker Compose
          run: |
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d --build

  clear:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Clean build cache
        run: |
          docker builder prune -a -f
      - name: Clean all temporary images
        run: |
          docker image prune -f
