name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted # Chạy trên self-hosted runner của bạn

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images using Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
