name: store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build docker image locally
        run: docker-compose build

      - name: Stop old container (if running)
        run: |
          docker-compose down || echo "No container running"

      - name: Start new container with Docker Compose
        run: docker-compose up -d --force-recreate

      - name: Clean up unused docker images
        run: |
          docker builder prune -a -f
          docker image prune -f
