name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Remove existing container demo-web-1 if exists
        run: |
          docker rm -f demo-web-1 || true

      - name: Build and deploy the latest version
        run: |
          docker-compose -f docker-compose.yml build --no-cache
          docker-compose -f docker-compose.yml up -d --force-recreate

      - name: Clean up Docker build cache
        run: |
          docker builder prune -af

      - name: Remove dangling images and volumes
        run: |
          docker image prune -af
          docker volume prune -f
